### ISSUE TITLE
Got error while capturing my module.

### ISSUE THREAD

**Issue by hongseokyoon** [Stratus3D/eflambe#49]
I got error while using flame_on and I think it's caused from eflambe. 

https://github.com/DockYard/flame_on/issues/46

```
> :eflambe.capture({MyWeb.MyController, :webpage, 2}, 3, [output_format: :brendan_gregg, open: :speedscope])


[error] #PID<0.2361.0> running MyWeb.Endpoint (connection #PID<0.2359.0>, stream id 1) terminated

..omitted..

** (exit) an exception was raised:
    ** (ArgumentError) errors were found at the given arguments:

  * 1st argument: invalid spec for pid or port

        :erlang.trace(#PID<0.2361.0>, true, [{:tracer, #PID<0.2366.0>}, :call, :return_to, :running, :procs, :garbage_collection, :arity, :timestamp, :set_on_spawn])
        (eflambe 0.3.1) /Users/hongseok/dev/tapjoy/offerwall_service/deps/eflambe/src/eflambe_server.erl:83: :eflambe_server.start_capture_trace/1
        (eflambe 0.3.1) /Users/hongseok/dev/tapjoy/offerwall_service/deps/eflambe/src/eflambe_server.erl:146: anonymous fn/2 in :eflambe_server.init/1
        lib/my_web/controllers/get_offers_controller.ex:1: MyWeb.GetOffersController_meck_original.action/2
        lib/my_web/controllers/get_offers_controller.ex:1: MyWeb.GetOffersController_meck_original.phoenix_controller_pipeline/2
        (phoenix 1.6.2) lib/phoenix/router.ex:355: Phoenix.Router.__call__/2
        (my 0.0.1) lib/my_web/endpoint.ex:1: MyWeb.Endpoint.plug_builder_call/2
        (my 0.0.1) lib/my_web/endpoint.ex:1: MyWeb.Endpoint."call (overridable 3)"/2
        (my 0.0.1) lib/plug/debugger.ex:136: MyWeb.Endpoint."call (overridable 4)"/2
        (my 0.0.1) lib/my_web/endpoint.ex:1: MyWeb.Endpoint.call/2
```

I've replace my app name with `my`.

elixir             1.12.3
erlang          24.1

**Comment by Stratus3D** [comment]
What version of eflambe are you using?

**Comment by Stratus3D** [comment]
Closing this due to lack of a response.
